### ISSUE TITLE
REST-DOCS api 문서화

### ISSUE THREAD

**Issue by Sehee-Lee-01** [spring-comes-to-us/springboot-board-jpa-SJ#8]
- [x]  게시글 작성 (POST "/posts")
- [x]  페이징 조회 (GET "/posts") 
- [x]  단건 조회 (GET "/posts/{id}")
- [x]  게시글 수정 (POST "/posts/{id}")

**Comment by shoeone96** [comment]
rest-docs 문서화 완료
<img width="1083" alt="스크린샷 2023-11-21 오후 4 58 42" src="https://github.com/spring-comes-to-us/springboot-board-jpa-SJ/assets/85065626/96fdbb7b-7679-4d0f-9907-907bf1935a83">
