### ISSUE TITLE
N + 1 문제 Post 조회시 발생

### ISSUE THREAD

**Issue by Sehee-Lee-01** [spring-comes-to-us/springboot-board-jpa-SJ#9]
Post 조회 기능 실행시 Post 조화 + User 조회 현상 @EntityGraph 도입하여 해결

**Comment by shoeone96** [comment]
단건 조회에서도 같은 문제가 발생해서 해결

쿼리를 여러 번 보내는 것보다 한번에 가져오는 게 건수가 많아질 수록 이 상황에서 좋다고 판단하여 적용
추후 테스트로 동작 시간 측정 예정

적용 전

<img src = "https://github.com/spring-comes-to-us/springboot-board-jpa-SJ/assets/85065626/1d19d9e2-997c-4d5a-9ff1-20819642b4d4" width = "1000px">  </br>

     

  

적용 후

<img src = "https://github.com/spring-comes-to-us/springboot-board-jpa-SJ/assets/85065626/5d90a1e4-53ea-479e-8ce7-a6a4082b42be" width = "1000px">
